### ISSUE TITLE
"Requests"?

### ISSUE THREAD

**Issue by NoahWL1** [Manevolent/EggCrack#16]
Hi, sorry that this isn't really an issue, but I have a quick question that I also think should be added to the Wiki.  What does the "Requests" section mean in the status tab of Eggcrack?  I've noticed it starts out at 1, and gradually rises as the program runs.  What does it mean?  Thanks!

**Comment by Manevolent** [comment]
Requests are total requests made for the authentication service you're using. I believe a request is tallied once the proxy returns an HTTP code, be it an error or otherwise.

An attempt is tallied when the response from the authentication service is handled as either a successful or unsuccessful login.

There are cases when the response cannot be parsed as a Mojang response (e.g. dead/bad proxy), but these are still considered requests.
