### ISSUE TITLE
Version 1.8 $$$setupUI$$$()

### ISSUE THREAD

**Issue by Mongogamer** [Manevolent/EggCrack#25]
So I decided to update version 1.8 with the new Mojang API changes as version 2.0 is very slow. I managed to fix all of the API requests but I ran into a problem that prevents me from starting the program. Whenever I try to run the fixed code in Eclipse I get the error

`Exception in thread "main" java.lang.Error: Unresolved compilation problem:` 
	`The method $$$setupUI$$$() is undefined for the type Main`
	`at com.teamlixo.eggcrack.Main.<init>(Main.java:63)`
	`at com.teamlixo.eggcrack.Main.main(Main.java:328)`

Do you have any suggestion on how to fix this error? Simply commenting it out doesn't help since contentPane can not be null.
I would greatly appreciate any help with this as there is no documentation for this version available.

**Comment by Manevolent** [comment]
EggCrack 1.8 and 2.0 were both created in IntelliJ IDEA, and any forms will have the $$$setupUI$$$() methods which are created by the IDE at compile-time. In EggCrack 1.8, the default behavior is used, which basically injects the layout code in $$$setupUI$$$() into the class files, and not the source files. Since EggCrack 2.0 is on GitHub, this UI code is kept in the Java source.

Basically you're going to need to either re-generate that method (in IDEA or something) or manually specify its calls, which would get tricky. I think this is all generated from these "form" files which IDEA uses, and I'm not sure if those are pushed into the JAR -- that might be a problem for you if the existing $$$setupUI$$$ isn't decompiling.

**Comment by Mongogamer** [comment]
I just tried to run the code in IntelliJ but ended up with the same result. Apparently the form files are not in the decompiled jar and without them IntelliJ can't re-generate the method. It also seems like some of the imports and method names were corrupted during the decompilation so it throws a few hundred errors at me. I guess I will have to find a different workaround. Thanks for the help anyways.
